name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn install
      - run: echo "VITE_INLINE_RUNTIME_CHUNK=false" > .env
      - run: yarn build
      - name: archive source code
        run: |
          git archive --output source.zip HEAD -- ":!.github"
          unzip -l source.zip
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: source.zip
  firefox:
    name: Submit (Firefox)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: try linting artifact
        run: |
          npx web-ext lint --source-dir build

      - run: tree source
      - run: tree build
